name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: "1.23"
      - name: Validate
        if: matrix.os == 'ubuntu-22.04'
        run: make validate
      - name: Run Tests
        run: make test